heat_template_version: 2015-04-30

description: >
  Tests openstack by creating VM, private network, and attaches 1G volume. Need cirros image, define flavor explicitly, else uses os.small.

parameters:

  image:
    type: string
    default: cirros

  flavor:
    type: string
    default: os.small

resources:

  private_net:
    type: OS::Neutron::Net
    properties:
      name: private-net

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net }
      cidr: 192.168.254.0/24
      gateway_ip: 192.168.254.1

  default_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 22
          port_range_max: 22
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0

  testVolume:
    type: OS::Cinder::Volume
    properties:
      name: "testVolume"
      size: 1

  attach_test_volume:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: testVolume }
      instance_uuid: { get_resource: testInstance }
      mountpoint: /dev/vdb
      
  testInstance_port:
    type: OS::Neutron::Port
    properties:
      security_groups:
        - { get_resource: default_secgroup }
      network: { get_resource: private_net }

  testInstance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image } 
      networks:
        - port: { get_resource: testInstance_port }
      flavor: { get_param: flavor }


