- name: Enabling syslog - nova,neutron
  ini_file:
    dest: "{{ item }}"
    section: DEFAULT
    state: present
    option: use_syslog
    value: true
  with_items:
    - /etc/nova/nova.conf
    - /etc/neutron/neutron.conf

- name: Setting syslog facility - nova
  ini_file:
    dest: /etc/nova/nova.conf
    section: DEFAULT
    state: present
    option: syslog_log_facility
    value: LOG_LOCAL0
  notify: restart nova

- name: Setting syslog facility - neutron
  ini_file:
    dest: /etc/neutron/neutron.conf
    section: DEFAULT
    state: present
    option: syslog_log_facility
    value: LOG_LOCAL1
  notify: restart neutron

- name: Enabling syslog - controllers,
  ini_file:
    dest: "{{ item }}"
    section: DEFAULT
    state: present
    option: use_syslog
    value: true
  with_items:
    - /etc/glance/glance-api.conf
    - /etc/glance/glance-registry.conf
    - /etc/cinder/cinder.conf
    - /etc/keystone/keystone.conf
    - /etc/ceilometer/ceilometer.conf
    - /etc/aodh/aodh.conf
  when: inventory_hostname in groups["controllers"]
    
- name: Setting syslog facility - glance api
  ini_file: 
    dest: /etc/neutron/neutron.conf
    section: DEFAULT
    state: present
    option: syslog_log_facility
    value: LOG_LOCAL2
  when: inventory_hostname in groups["controllers"]
  notify: restart glance

- name: Setting syslog facility - glance registry
  ini_file:
    dest: /etc/glance/glance-registry.conf
    section: DEFAULT
    state: present
    option: syslog_log_facility
    value: LOG_LOCAL3
  when: inventory_hostname in groups["controllers"]
  notify: restart glance

- name: Setting syslog facility - Cinder
  ini_file:
    dest: /etc/cinder/cinder.conf
    section: DEFAULT
    state: present
    option: syslog_log_facility
    value: LOG_LOCAL4
  when: inventory_hostname in groups["controllers"]
  notify: restart cinder

- name: Setting syslog facility - Keystone
  ini_file:
    dest: /etc/keystone/keystone.conf
    section: DEFAULT
    state: present
    option: syslog_log_facility
    value: LOG_LOCAL5
  when: inventory_hostname in groups["controllers"]
  notify: restart httpd

- name: Setting syslog facility - Ceilometer
  ini_file:
    dest: /etc/ceilometer/ceilometer.conf
    section: DEFAULT
    state: present
    option: syslog_log_facility
    value: LOG_LOCAL6
  when: inventory_hostname in groups["controllers"]
  notify: restart ceilometer

- name: Setting syslog facility
  ini_file:
    dest: /etc/aodh/aodh.conf
    section: DEFAULT
    state: present
    option: syslog_log_facility
    value: LOG_LOCAL7
  when: inventory_hostname in groups["controllers"]

- name: copy client logging configuration
  copy:
    content: "*.* @{{ log_server }}:514\n"
    dest: /etc/rsyslog.d/client.conf
    owner: root
    group: root
    mode: 0664
  notify: restart rsyslog
