heat_template_version: 2015-04-30

description: simple stack with instance and private network

parameters:

  image:
    type: string
    default: cirros

resources:

  private_net:
    type: OS::Neutron::Net
    properties:
      name: private-net

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net }
      cidr: 192.168.254.0/24
      gateway_ip: 192.168.254.254 

  def_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 22
          port_range_max: 22
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0

  instance_1_port:
    type: OS::Neutron::Port
    properties:
      security_groups:
        - { get_resource: def_secgroup }
      network: { get_resource: private_net }

  instance_1:
    type: OS::Nova::Server
    properties:
      image: { get_param: image } 
      networks:
        - port: { get_resource: instance_1_port }
      flavor: os.small

