- name: Registering Red Hat system
  include_tasks: register_redhat.yml
  when: ansible_distribution == 'Red Hat Enterprise Linux

- name: Running extra tasks
  include_tasks: extras.yml

- name: Update the undercloud
  yum:
    name: "*"
    state: latest
  register: update

- name: Create group stack
  group:
    name: stack
    state: present

- name: Create user stack
  user:
    name: stack
    group: stack
    createhome: yes
    move_home: yes
    home: "{{ stackhome }}"
    password: "{{ stack_pass }}"
    state: present

- name: creat images directory
  file:
    path: "{{ stackhome }}/images"
    state: directory
    owner: stack
    group: stack
    mode: 0755
    setype: user_home_t

- name: create templates directory
  file:
    path: "{{ stackhome }}/templates"
    state: directory
    owner: stack
    group: stack
    mode: 0755
    setype: user_home_t

- name: create /etc/sudoers.d/stack
  copy:
    dest: /etc/sudoers.d/stack
    mode: 0440
    content: "stack ALL=(root) NOPASSWD:ALL"
    owner: root
    group: root

- name: Configure hostname
  hostname:
    name: "{{ shortname }}.{{ domainname }}"

- name: Rebooting node
  shell: sleep 3 && /sbin/reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: Waiting on node to return
  wait_for:
    host: "{{ ansible_ssh_host }}"
    state: started
    port: 22
    delay: 30
    timeout: 600
    connect_timeout: 10
  delegate_to: localhost

- name: Install undercloud packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - crudini
    - python-tripleoclient
    - rhosp-director-images
    - rhosp-director-images-ipa
    - tmux

- name: Copying undercloud.conf
  copy:
    src: "{{ undercloud_conf }}"
    dest: "{{ stackhome }}/undercloud.conf"
    owner: stack
    group: stack

- name: Check for undercloud installation
  shell: "tail -n 12 /home/stack/.instack/install-undercloud.log | head -n 1"
  register: install_status
  failed_when: false
  changed_when: false

- name: Installation of the Undercloud (Please be patient)
  shell: openstack undercloud install
  become: yes
  become_user: stack
  async: 14400
  poll: 60
  when: install_status.stdout != "Undercloud install complete."

- name: Extracting images
  unarchive:
    remote_src: yes
    src: "{{ item }}"
    dest: "{{ stackhome }}/images"
    creates: overcloud-full.qcow2
  become: yes
  become_user: stack
  with_items:
    - /usr/share/rhosp-director-images/overcloud-full-latest-11.0.tar
    - /usr/share/rhosp-director-images/ironic-python-agent-latest-11.0.tar

- name: Uploading images to glance
  shell: ". /home/stack/stackrc && openstack overcloud image upload --image-path /home/stack/images/"
  become: yes
  become_user: stack

- name: Get pubkey
  command: cat /home/stack/.ssh/id_rsa.pub
  register: pubkey

- name: inject pubkey
  lineinfile:
    state: present
    create: yes
    path: /root/.ssh/authorized_keys
    mode: 0600
    owner: root
    group: root
    setype: ssh_home_t
    line: "{{ pubkey.stdout }}"
  delegate_to: 127.0.0.1

- name: Running instackenv.sh
  script: "../files/{{ instackenv_sh }}"
  args:
    creates: "{{ stackhome }}/instackenv.json"
  become: yes
  become_user: stack

- name: Importing ironic nodes
  shell: ". /home/stack/stackrc && openstack overcloud node import --json /home/stack/instackenv.json"
  become: yes
  become_user: stack

