heat_template_version: 2014-10-16

description: >
  * Fix SSH latency by setting UseDNS to 'no'

parameters:
  servers:
    type: json
  DeployIdentifier:
    type: string

resources:
  CustomExtraConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash
        sed -i 's/#UseDNS.*//' /etc/ssh/sshd_config
        if grep "^UseDNS" /etc/ssh/sshd_config; then
        sed -i 's/^UseDNS.*/UseDNS no/' /etc/ssh/sshd_config
        else echo -e "\nUseDNS no" >> /etc/ssh/sshd_config; fi
        systemctl restart sshd

  CustomExtraDeployments:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      servers:  {get_param: servers}
      config: {get_resource: CustomExtraConfig}
      actions: ['CREATE','UPDATE']
      input_values:
        deploy_identifier: {get_param: DeployIdentifier}
